### ISSUE TITLE
lost @font-face rule when compressing css

### ISSUE THREAD

**Issue by snotons** [Cerdic/CSSTidy#66]
Hi,
I lost effect of @font-face rule from my perso.css when compressing css on my site (SPIP 3.2.11).
Regards.

**Comment by Cerdic** [comment]
Without any detail like at least an extract of the original @font-face rule and the compressed css resulting I won't be able to do anything.

Moreover, this could be as well an issue in SPIP itself instead of CSSTidy. 

So I would advice to fill an issue in SPIP issue tracker with a code sample that allow to reproduce the issue, and if it's a CSSTidy issue I will propagate the problem here. Meanwhile I'm closing this issue
